import { DetailDeliveryTmplSchema } from '../schemas';
export const DetailDeliveryTmplSchemaMocks: DetailDeliveryTmplSchema = {
  providerShippings: [
    {
      id: 2,
      providerId: 2,
      name: '서울물류센터',
      shippingPolicy: {
        costType: 'IFPAY',
        payCost: 5000,
        ifpayFreePrice: 90000,
        ifpayCost: 6000,
      },
      returnCost: 2500,
      returnAddCost: 0,
      defaultExportingDelays: 1,
      extraAddCosts: null,
      sendingAddress: {
        postCode: '12345',
        address: '주소',
        addressDetail: '상세주소',
        phoneNumber: '123-4556-9999',
      },
      returnAddress: null,
      deliveryName: 'CJ대한통운',
      createdDate: 1621545193000,
      isDefault: false,
    },
    {
      id: 29,
      providerId: 1,
      name: '천안물류센터',
      shippingPolicy: {
        costType: 'PAY',
        payCost: 5500,
        ifpayFreePrice: 0,
        ifpayCost: 0,
      },
      returnCost: 2500,
      returnAddCost: 0,
      defaultExportingDelays: 1,
      extraAddCosts: [
        {
          region: 'JEJU',
          price: 7500,
        },
        {
          region: 'ETC',
          price: 5500,
        },
      ],
      sendingAddress: {
        postCode: '13641',
        address: '경기도',
        addressDetail: '성남시',
        phoneNumber: '010-3754-1436',
      },
      returnAddress: {
        postCode: '13641',
        address: '경기도',
        addressDetail: '성남시',
        phoneNumber: '010-3754-1436',
      },
      deliveryName: 'CJ대한통운',
      createdDate: 1625797773000,
      isDefault: false,
    },
    {
      id: 52,
      providerId: 1,
      name: '파주물류센터',
      shippingPolicy: {
        costType: 'FREE',
        payCost: 0,
        ifpayFreePrice: 0,
        ifpayCost: 0,
      },
      returnCost: 0,
      returnAddCost: 0,
      defaultExportingDelays: 2,
      extraAddCosts: [
        {
          region: 'JEJU',
          price: 0,
        },
        {
          region: 'ETC',
          price: 0,
        },
      ],
      sendingAddress: {
        postCode: '5208',
        address: '서울 강동구 풍산로 237',
        addressDetail: '1',
        phoneNumber: '010-3754-1436',
      },
      returnAddress: {
        postCode: '6027',
        address: '서울 강남구 압구정로 102',
        addressDetail: '1',
        phoneNumber: '010-3754-1436',
      },
      deliveryName: 'CJ대한통운',
      createdDate: 1627621751000,
      isDefault: true,
    },
    {
      id: 53,
      providerId: 1,
      name: '11',
      shippingPolicy: {
        costType: 'FREE',
        payCost: 0,
        ifpayFreePrice: 0,
        ifpayCost: 0,
      },
      returnCost: 3333,
      returnAddCost: 0,
      defaultExportingDelays: 1,
      extraAddCosts: [
        {
          region: 'JEJU',
          price: 0,
        },
        {
          region: 'ETC',
          price: 0,
        },
      ],
      sendingAddress: {
        postCode: '6027',
        address: '서울 강남구 압구정로 102',
        addressDetail: '12',
        phoneNumber: '010-3754-1436',
      },
      returnAddress: {
        postCode: '61447',
        address: '광주 동구 2순환로 575',
        addressDetail: '3',
        phoneNumber: '010-3754-1436',
      },
      deliveryName: 'CJ대한통운',
      createdDate: 1627638161000,
      isDefault: false,
    },
    {
      id: 54,
      providerId: 1,
      name: '112',
      shippingPolicy: {
        costType: 'FREE',
        payCost: 0,
        ifpayFreePrice: 0,
        ifpayCost: 0,
      },
      returnCost: 3333,
      returnAddCost: 0,
      defaultExportingDelays: 1,
      extraAddCosts: [
        {
          region: 'JEJU',
          price: 0,
        },
        {
          region: 'ETC',
          price: 0,
        },
      ],
      sendingAddress: {
        postCode: '28787',
        address: '충북 청주시 상당구 1순환로 1202-1',
        addressDetail: '12',
        phoneNumber: null,
      },
      returnAddress: {
        postCode: '18568',
        address: '경기 화성시 우정읍 3.1만세로 1',
        addressDetail: '2323',
        phoneNumber: null,
      },
      deliveryName: 'CJ대한통운',
      createdDate: 1627638224000,
      isDefault: false,
    },
    {
      id: 55,
      providerId: 1,
      name: '1',
      shippingPolicy: {
        costType: 'FREE',
        payCost: 0,
        ifpayFreePrice: 0,
        ifpayCost: 0,
      },
      returnCost: 0,
      returnAddCost: 0,
      defaultExportingDelays: 1,
      extraAddCosts: [
        {
          region: 'JEJU',
          price: 20,
        },
        {
          region: 'ETC',
          price: 2,
        },
      ],
      sendingAddress: {
        postCode: '06027',
        address: '서울 강남구 압구정로 102',
        addressDetail: '1',
        phoneNumber: null,
      },
      returnAddress: {
        postCode: '61738',
        address: '광주 남구 2순환로 1508',
        addressDetail: '2',
        phoneNumber: null,
      },
      deliveryName: 'CJ대한통운',
      createdDate: 1627638550000,
      isDefault: false,
    },
  ],
};
