import { PaginationResponse } from '@schemas/PaginationSchema';
import { GoodsListSchema } from '../schemas';

export const ListSchemaMocks: PaginationResponse<GoodsListSchema> = {
  content: [
    {
      id: 22640,
      requestMemo: '요청결과 메모',
      name: '파트너 등록 #3 _ 다중옵션_copy',
      brand: {
        id: 21247,
        name: '벨레',
      },
      provider: {
        id: 21252,
        name: '(주) 벨레 (WELLE Co., Ltd)',
      },
      status: 'UNSOLD',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'UNLIMIT',
        userMaxPurchaseEa: null,
        limitedType: 'NONE',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'PARCEL',
        shippingPolicy: 'GOODS',
        goodsShippingPolicy: 'UNLIMIT',
        unLimitShippingPrice: 4000,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 0,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 2,
            name: '패션/잡화',
          },
          two: {
            id: 129,
            name: '남성패션',
          },
          three: {
            id: 201,
            name: '니트웨어',
          },
        },
      ],
      primaryImage: {
        id: 50297,
        path: 'goods/20220616/9de5a003-a19a-493e-8dd1-fad14497bc8e.jpeg',
        originalFileName: 'b08d33fb-1b70-4615-b9ca-6e91c644a02a.jpeg',
        extension: 'jpeg',
        width: 512,
        height: 512,
      },
      consumerPrice: 2000,
      price: 1000,
      salesStartDate: 1656398760000,
      salesEndDate: null,
      displayStartDate: 1656398760000,
      keyword: [
        {
          id: 8,
          name: '홈스타일링',
        },
      ],
      requestStatus: '승인',
    },
    {
      id: 22616,
      requestMemo: '요청결과 메모',
      name: '[테스트 상품] 시엔느 파트너 등록',
      brand: {
        id: 21210,
        name: '시엔느',
      },
      provider: {
        id: 21226,
        name: '주식회사 시엔느',
      },
      status: 'NORMAL',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'LIMIT',
        userMaxPurchaseEa: 10,
        limitedType: 'NONE',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'DIRECT',
        shippingPolicy: 'GOODS',
        goodsShippingPolicy: 'UNLIMIT',
        unLimitShippingPrice: 3500,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 0,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 1,
            name: '뷰티',
          },
          two: {
            id: 10,
            name: '스킨케어',
          },
          three: {
            id: 20,
            name: '스킨/토너',
          },
        },
      ],
      primaryImage: {
        id: 50420,
        path: 'goods/20220620/e1aae781-3366-4397-a95d-2be63ca1f9a4.jpeg',
        originalFileName: 'test.jpeg',
        extension: 'jpeg',
        width: 512,
        height: 512,
      },
      consumerPrice: 10000,
      price: 5000,
      salesStartDate: 1655714280000,
      salesEndDate: 4102412399000,
      displayStartDate: 1655714280000,
      keyword: [],
      requestStatus: '승인',
    },
    {
      id: 22615,
      requestMemo: '요청결과 메모',
      name: '에디상품 - (반려후) 단일옵션후 다중옵션 변환',
      brand: {
        id: 21247,
        name: '벨레',
      },
      provider: {
        id: 21252,
        name: '(주) 벨레 (WELLE Co., Ltd)',
      },
      status: 'NORMAL',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'UNLIMIT',
        userMaxPurchaseEa: null,
        limitedType: 'NONE',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'PARCEL',
        shippingPolicy: 'SHOP',
        goodsShippingPolicy: 'UNLIMIT',
        unLimitShippingPrice: 0,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 0,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 4,
            name: 'IT/테크',
          },
          two: {
            id: 354,
            name: '청소가전',
          },
          three: {
            id: 367,
            name: '청소기',
          },
        },
      ],
      primaryImage: {
        id: 50418,
        path: 'goods/20220620/a68697a2-4f44-4f49-bfa2-607d931369cf.jpeg',
        originalFileName: '95ac4475-41f7-4d42-abd5-348e99e6f846.jpeg',
        extension: 'jpeg',
        width: 512,
        height: 512,
      },
      consumerPrice: 4000,
      price: 3000,
      salesStartDate: 1655713320000,
      salesEndDate: 4102412399000,
      displayStartDate: 1655713320000,
      keyword: [],
      requestStatus: '승인',
    },
    {
      id: 22610,
      requestMemo: '요청결과 메모',
      name: '파트너 등록 #3 _ 다중옵션',
      brand: {
        id: 21247,
        name: '벨레',
      },
      provider: {
        id: 21252,
        name: '(주) 벨레 (WELLE Co., Ltd)',
      },
      status: 'UNSOLD',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'UNLIMIT',
        userMaxPurchaseEa: null,
        limitedType: 'NONE',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'PARCEL',
        shippingPolicy: 'GOODS',
        goodsShippingPolicy: 'UNLIMIT',
        unLimitShippingPrice: 4000,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 0,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 2,
            name: '패션/잡화',
          },
          two: {
            id: 129,
            name: '남성패션',
          },
          three: {
            id: 201,
            name: '니트웨어',
          },
        },
      ],
      primaryImage: {
        id: 50297,
        path: 'goods/20220616/9de5a003-a19a-493e-8dd1-fad14497bc8e.jpeg',
        originalFileName: 'b08d33fb-1b70-4615-b9ca-6e91c644a02a.jpeg',
        extension: 'jpeg',
        width: 512,
        height: 512,
      },
      consumerPrice: 2000,
      price: 1000,
      salesStartDate: 1655456700000,
      salesEndDate: 4102412399000,
      displayStartDate: 1655456700000,
      keyword: [
        {
          id: 8,
          name: '홈스타일링',
        },
      ],
      requestStatus: '승인',
    },
    {
      id: 22607,
      requestMemo: '요청결과 메모',
      name: '[파트너 등록] 시엔느 파트너 등록 테스트 상품 이다',
      brand: {
        id: 21210,
        name: '시엔느',
      },
      provider: {
        id: 21226,
        name: '주식회사 시엔느',
      },
      status: 'NORMAL',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'LIMIT',
        userMaxPurchaseEa: 10,
        limitedType: 'NONE',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'PARCEL',
        shippingPolicy: 'SHOP',
        goodsShippingPolicy: 'UNLIMIT',
        unLimitShippingPrice: 0,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 0,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 2,
            name: '패션/잡화',
          },
          two: {
            id: 128,
            name: '여성패션',
          },
          three: {
            id: 186,
            name: '티셔츠',
          },
        },
      ],
      primaryImage: {
        id: 50295,
        path: 'goods/20220616/9749f700-a868-40a8-b4de-f2671a40fc82.jpeg',
        originalFileName: 'test.jpeg',
        extension: 'jpeg',
        width: 512,
        height: 512,
      },
      consumerPrice: 8800,
      price: 7500,
      salesStartDate: 1655362560000,
      salesEndDate: 4102412399000,
      displayStartDate: 1655362560000,
      keyword: [],
      requestStatus: '승인',
    },
    {
      id: 22603,
      requestMemo: '요청결과 메모',
      name: '스탠바이미',
      brand: {
        id: 21273,
        name: 'May',
      },
      provider: {
        id: 21268,
        name: 'May test',
      },
      status: 'NORMAL',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'UNLIMIT',
        userMaxPurchaseEa: null,
        limitedType: 'NONE',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'PARCEL',
        shippingPolicy: 'SHOP',
        goodsShippingPolicy: 'UNLIMIT',
        unLimitShippingPrice: 0,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 0,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 4,
            name: 'IT/테크',
          },
          two: {
            id: 356,
            name: '디지털가전',
          },
          three: {
            id: 379,
            name: '모니터',
          },
        },
      ],
      primaryImage: {
        id: 50197,
        path: 'goods/20220613/ef8aeb27-4c96-44a3-b655-8b2c2163ba2d.jpg',
        originalFileName: '스크린샷 2022-06-13 오후 6.48.57.png',
        extension: 'jpg',
        width: 930,
        height: 846,
      },
      consumerPrice: 100000,
      price: 99000,
      salesStartDate: 1655113200000,
      salesEndDate: 4102412399000,
      displayStartDate: 1655113200000,
      keyword: [
        {
          id: 1,
          name: '전체',
        },
        {
          id: 12,
          name: 'BENEFITS',
        },
      ],
      requestStatus: '승인',
    },
    {
      id: 22595,
      requestMemo: '요청결과 메모',
      name: '쇼카콜라 2종세트 (+전용쇼핑백 증정)_코피_copy',
      brand: {
        id: 21201,
        name: 'WeenyBeeny',
      },
      provider: {
        id: 21203,
        name: '(주)씨믹스',
      },
      status: 'UNSOLD',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'UNLIMIT',
        userMaxPurchaseEa: null,
        limitedType: 'NONE',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'DIRECT',
        shippingPolicy: 'GOODS',
        goodsShippingPolicy: 'IFPAY',
        unLimitShippingPrice: 0,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 1000,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 5,
            name: '식품',
          },
          two: {
            id: 159,
            name: '가공식품',
          },
          three: {
            id: 426,
            name: '생수/음료/주류',
          },
        },
      ],
      primaryImage: {
        id: 22060,
        path: 'goods/20220215/8761498d-af32-4101-8778-cccb292ea065.jpeg',
        originalFileName: '쇼카콜라 2종세트 본품이미지.jpg',
        extension: 'jpg',
        width: 550,
        height: 550,
      },
      consumerPrice: 6000,
      price: 2000,
      salesStartDate: 1654740960000,
      salesEndDate: 4102412399000,
      displayStartDate: 1654740960000,
      keyword: [
        {
          id: 1,
          name: '전체',
        },
        {
          id: 5,
          name: 'YUMMY',
        },
      ],
      requestStatus: '승인',
    },
    {
      id: 22591,
      requestMemo: '요청결과 메모',
      name: "alice_'test'_2_copy",
      brand: {
        id: 21204,
        name: '스티키몬스터랩',
      },
      provider: {
        id: 21219,
        name: '㈜알엑스씨',
      },
      status: 'UNSOLD',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'UNLIMIT',
        userMaxPurchaseEa: null,
        limitedType: 'GOODS',
        limitedGoodsEa: 11,
      },
      shippingInfo: {
        shippingMethod: 'PARCEL',
        shippingPolicy: 'SHOP',
        goodsShippingPolicy: 'UNLIMIT',
        unLimitShippingPrice: 0,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 0,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 2,
            name: '패션/잡화',
          },
          two: {
            id: 128,
            name: '여성패션',
          },
          three: {
            id: 184,
            name: '원피스',
          },
        },
      ],
      primaryImage: {
        id: 49959,
        path: 'goods/20220520/11ac8687-3910-4135-96b9-0f998600b606.jpg',
        originalFileName: 'KakaoTalk_Photo_2022-05-20-11-44-25.png',
        extension: 'jpg',
        width: 537,
        height: 382,
      },
      consumerPrice: 3000,
      price: 2550,
      salesStartDate: 1654572180000,
      salesEndDate: 4102412399000,
      displayStartDate: 1654572180000,
      keyword: [],
      requestStatus: '승인',
    },
    {
      id: 22590,
      requestMemo: '요청결과 메모',
      name: "alice_'test'_2",
      brand: {
        id: 21254,
        name: '하이라이트',
      },
      provider: {
        id: 21219,
        name: '㈜알엑스씨',
      },
      status: 'NORMAL',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'UNLIMIT',
        userMaxPurchaseEa: null,
        limitedType: 'OPTION',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'PARCEL',
        shippingPolicy: 'SHOP',
        goodsShippingPolicy: 'UNLIMIT',
        unLimitShippingPrice: 0,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 0,
        ifpayFreePrice: 0,
      },
      categories: [
        {
          one: {
            id: 2,
            name: '패션/잡화',
          },
          two: {
            id: 128,
            name: '여성패션',
          },
          three: {
            id: 184,
            name: '원피스',
          },
        },
      ],
      primaryImage: {
        id: 49959,
        path: 'goods/20220520/11ac8687-3910-4135-96b9-0f998600b606.jpg',
        originalFileName: 'KakaoTalk_Photo_2022-05-20-11-44-25.png',
        extension: 'jpg',
        width: 537,
        height: 382,
      },
      consumerPrice: 3000,
      price: 2550,
      salesStartDate: 1654242960000,
      salesEndDate: 1656559379000,
      displayStartDate: 1654242960000,
      keyword: [],
      requestStatus: '승인',
    },
    {
      id: 22588,
      requestMemo: '요청결과 메모',
      name: "[특문테스트] '라'이프시리즈 라이트 매트리스 내추럴_copy",
      brand: {
        id: 21204,
        name: '스티키몬스터랩',
      },
      provider: {
        id: 21201,
        name: '아파트멘터리 주식회사',
      },
      status: 'NORMAL',
      type: 'NORMAL',
      goodsKind: 'REAL',
      purchaseInfo: {
        minPurchaseLimit: 'UNLIMIT',
        minPurchaseEa: null,
        maxPurchaseLimit: 'UNLIMIT',
        maxPurchaseEa: null,
        userMaxPurchaseLimit: 'UNLIMIT',
        userMaxPurchaseEa: null,
        limitedType: 'NONE',
        limitedGoodsEa: null,
      },
      shippingInfo: {
        shippingMethod: 'PARCEL',
        shippingPolicy: 'GOODS',
        goodsShippingPolicy: 'IFPAY',
        unLimitShippingPrice: 0,
        limitShippingEa: 0,
        limitShippingPrice: 0,
        ifpayCost: 4000,
        ifpayFreePrice: 50000,
      },
      categories: [
        {
          one: {
            id: 3,
            name: '리빙/생활',
          },
          two: {
            id: 143,
            name: '가구',
          },
          three: {
            id: 274,
            name: '침대',
          },
        },
      ],
      primaryImage: {
        id: 29616,
        path: 'goods/20220228/a9850af1-f874-4d17-a50a-42e6eaae94e2.jpg',
        originalFileName: '라이프시리즈 라이트 매트리스 내추럴.png',
        extension: 'jpg',
        width: 512,
        height: 512,
      },
      consumerPrice: 450000,
      price: 450000,
      salesStartDate: 1654223280000,
      salesEndDate: 4102412399000,
      displayStartDate: 1654223280000,
      keyword: [
        {
          id: 8,
          name: '홈스타일링',
        },
        {
          id: 1,
          name: '전체',
        },
      ],
      requestStatus: '승인',
    },
  ],
  last: false,
  totalElements: 31,
  totalPages: 4,
  first: true,
  numberOfElements: 10,
  size: 10,
};
