import { PaginationResponse } from '@schemas/PaginationSchema';
import { BusinessType, ProviderSchema } from '../schemas';

export const providerSchemaMock: PaginationResponse<ProviderSchema> = {
  content: [
    {
      id: 2,
      name: '엘리쓰',
      brandResponses: [],
      createdDate: 1621545294000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 0,
    },
    {
      id: 3,
      name: '엘리쓰2',
      brandResponses: [],
      createdDate: 1621545294000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 0,
    },
    {
      id: 4,
      name: '엘리쓰3',
      brandResponses: [],
      createdDate: 1621545294000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 0,
    },
    {
      id: 37,
      name: '아모레퍼시픽',
      brandResponses: [
        {
          id: 15,
          name: '아모레퍼시픽',
        },
      ],
      createdDate: 1623638136000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 2,
    },
    {
      id: 38,
      name: '매일유업',
      brandResponses: [
        {
          id: 14,
          name: '매일유업',
        },
        {
          id: 17,
          name: '셀렉스',
        },
      ],
      createdDate: 1623719228000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 2,
    },
    {
      id: 45,
      name: '나이키',
      brandResponses: [
        {
          id: 2,
          name: '나이키',
        },
      ],
      createdDate: 1625109926000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 2,
    },
    {
      id: 46,
      name: '르까프',
      brandResponses: [
        {
          id: 19,
          name: 'MZ르까프2',
        },
        {
          id: 1,
          name: '르까프',
        },
        {
          id: 18,
          name: 'MZ르까프',
        },
        {
          id: 21,
          name: 'MZ르까프3',
        },
      ],
      createdDate: 1625563196000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 2,
    },
    {
      id: 47,
      name: '한섬',
      brandResponses: [
        {
          id: 22,
          name: '시스템옴므',
        },
        {
          id: 23,
          name: '타임옴므',
        },
      ],
      createdDate: 1625712130000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 1,
    },
    {
      id: 48,
      name: '아디다스',
      brandResponses: [
        {
          id: 4,
          name: '아디다스',
        },
      ],
      createdDate: 1626855218000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 1,
    },
    {
      id: 49,
      name: '신성통상',
      brandResponses: [
        {
          id: 28,
          name: '지오지아',
        },
      ],
      createdDate: 1626918350000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 1,
    },
    {
      id: 51,
      name: '입접사1 - 법인',
      brandResponses: [],
      createdDate: 1627285859000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 33,
      calculateCount: 0,
    },
    {
      id: 61,
      name: '리복',
      brandResponses: [],
      createdDate: 1627549554000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 100,
      calculateCount: 0,
    },
    {
      id: 66,
      name: '테스트-법인',
      brandResponses: [],
      createdDate: 1627810411000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 100,
      calculateCount: 1,
    },
    {
      id: 67,
      name: '일반 개인',
      brandResponses: [],
      createdDate: 1627818894000,
      businessType: 'PRIVATE' as BusinessType,
      commissionRate: 100,
      calculateCount: 0,
    },
    {
      id: 71,
      name: '법인1',
      brandResponses: [],
      createdDate: 1627819977000,
      businessType: 'CORPORATE' as BusinessType,
      commissionRate: 100,
      calculateCount: 0,
    },
    {
      id: 72,
      name: '111',
      brandResponses: [],
      createdDate: 1627820155000,
      businessType: 'INDIVISUAL' as BusinessType,
      commissionRate: 100,
      calculateCount: 0,
    },
    {
      id: 75,
      name: '123',
      brandResponses: [],
      createdDate: 1627820939000,
      businessType: 'PRIVATE' as BusinessType,
      commissionRate: 100,
      calculateCount: 0,
    },
    {
      id: 76,
      name: '123',
      brandResponses: [],
      createdDate: 1627821174000,
      businessType: 'INDIVISUAL' as BusinessType,
      commissionRate: 100,
      calculateCount: 0,
    },
    {
      id: 77,
      name: '123',
      brandResponses: [],
      createdDate: 1627821429000,
      businessType: 'INDIVISUAL' as BusinessType,
      commissionRate: 100,
      calculateCount: 0,
    },
    {
      id: 78,
      name: '1111',
      brandResponses: [],
      createdDate: 1627821540000,
      businessType: 'INDIVISUAL' as BusinessType,
      commissionRate: 100,
      calculateCount: 0,
    },
  ],
  last: false,
  totalElements: 56,
  totalPages: 3,
  first: true,
  numberOfElements: 20,
  size: 20,
};
